export const WORKOUT_TEMPLATES = [
  {
    id: 'stronglifts_a',
    type: 'A',
    name: 'Workout A',
    titleRu: 'Тренировка A',
    descRu: 'Присед, Жим лежа, Тяга, Пресс',
    exercises: [
      {
        exerciseId: 'squat',
        name: 'Приседания со штангой',
        nameEn: 'Squat',
        defaultSets: 3,
        defaultReps: 8,
        defaultWeightKg: 70,
        defaultRestSeconds: 90,
      },
      {
        exerciseId: 'bench_press',
        name: 'Жим штанги лежа',
        nameEn: 'Bench Press',
        defaultSets: 3,
        defaultReps: 8,
        defaultWeightKg: 60,
        defaultRestSeconds: 90,
      },
      {
        exerciseId: 'barbell_row',
        name: 'Тяга штанги в наклоне',
        nameEn: 'Barbell Row',
        defaultSets: 3,
        defaultReps: 8,
        defaultWeightKg: 50,
        defaultRestSeconds: 90,
      },
      {
        exerciseId: 'situps',
        name: 'Подъемы корпуса',
        nameEn: 'Situps',
        defaultSets: 3,
        defaultReps: 20,
        defaultWeightKg: 0,
        isBodyweight: true,
        defaultRestSeconds: 60,
      },
    ],
  },
  {
    id: 'stronglifts_b',
    type: 'B',
    name: 'Workout B',
    titleRu: 'Тренировка B',
    descRu: 'Становая, Жим стоя, Подтягивания, Планка',
    exercises: [
      {
        exerciseId: 'deadlift',
        name: 'Становая тяга',
        nameEn: 'Deadlift',
        defaultSets: 3,
        defaultReps: 8,
        defaultWeightKg: 90,
        defaultRestSeconds: 120,
      },
      {
        exerciseId: 'ohp',
        name: 'Армейский жим стоя',
        nameEn: 'Overhead Press',
        defaultSets: 3,
        defaultReps: 8,
        defaultWeightKg: 40,
        defaultRestSeconds: 90,
      },
      {
        exerciseId: 'pullups',
        name: 'Подтягивания широким хватом',
        nameEn: 'Pull-ups',
        defaultSets: 3,
        defaultReps: 8,
        defaultWeightKg: 0,
        isBodyweight: true,
        defaultRestSeconds: 90,
      },
      {
        exerciseId: 'plank',
        name: 'Планка на предплечьях',
        nameEn: 'Plank',
        defaultSets: 3,
        defaultReps: 1,
        targetSeconds: 60,
        isTimeBased: true,
        defaultWeightKg: 0,
        isBodyweight: true,
        defaultRestSeconds: 60,
      },
    ],
  },
];

export const THEME = {
  bg: 0x0a0d14,
  cardBg: 0x121724,
  cardBorder: 0x1f273b,
  primary: 0x10b981,     // Emerald 500
  primaryActive: 0x059669,
  accentCyan: 0x06b6d4,   // Cyan 500
  accentAmber: 0xf59e0b,  // Amber 500
  textWhite: 0xffffff,
  textMuted: 0x94a3b8,
  textDark: 0x64748b,
  danger: 0xef4444,
};
